Jugadores/Controllers/EventosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Jugadores.Models;
using Jugadores.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Jugadores.Controllers;

public class EventosController : Controller
{
    private ApplicationDbContext _context;

    public EventosController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Eventos()
    {
        var partidos = _context.Partidos.ToList();

        partidos.Add(new Partido { PartidoID = 0, Estadio = "SELECCIONE EL ESTADIO DONDE SE JUGÓ. . . " });
        ViewBag.PartidoID = new SelectList(partidos.OrderBy(j => j.PartidoID), "PartidoID", "Estadio");

        var jugadores = _context.Jugadores.ToList();

        jugadores.Add(new Jugador { JugadorID = 0, Nombre = "[TODOS LOS JUGADORES]" });
        ViewBag.JugadorID = new SelectList(jugadores.OrderBy(j => j.JugadorID), "JugadorID", "Nombre");

        return View();
    }

    public JsonResult TraerDetallePartido(int PartidoID)
    {
        // Primero, obtienes el partido con el ID especificado, incluyendo la relación con el jugador
        var partido = _context.Partidos
                              .Include(p => p.Jugador)
                              .FirstOrDefault(p => p.PartidoID == PartidoID);

        // Luego, verificas si el partido existe
        if (partido == null)
        {
            return Json(null); // o podrías devolver un mensaje de error
        }

        // Después, haces la proyección para seleccionar solo los datos necesarios
        var partidoDto = new
        {
            Nombre = partido.Jugador.Nombre,
            FechaPartido = partido.FechaPartido
        };

        // Finalmente, devuelves los datos proyectados como JSON
        return Json(partidoDto);
    }

    public JsonResult ListadoEventos(int? EventoPartidoID, int? JugadorID)
    {
        var listadoEventos = _context.EventoPartidos.Include(l => l.Partido).Include(l => l.Partido.Jugador).ToList();

        if (EventoPartidoID != null)
        {
            listadoEventos = _context.EventoPartidos.Where(l => l.EventoPartidoID == EventoPartidoID).ToList();
        }
        if (JugadorID != null && JugadorID != 0)
        {
            listadoEventos = _context.EventoPartidos.Where(l => l.Partido.JugadorID == JugadorID).ToList();
        }

        var listadoEventosMostrar = listadoEventos.Select(p => new VistaEventos
        {
            EventoPartidoID = p.EventoPartidoID,
            PartidoID = p.PartidoID,
            EstadioPartido = p.Partido.Estadio,
            NombreJugador = p.Partido.Jugador.Nombre,
            PuestoJugador = p.Partido.Jugador.Puesto,
            FechaPartido = p.Partido.FechaPartido,
            Descripcion = p.Descripcion
        }).ToList();

        return Json(listadoEventosMostrar);
    }

    public JsonResult GuardarEvento(int EventoPartidoID, int PartidoID, DateTime FechaEvento, string? Descripcion)
    {
        Descripcion = Descripcion.ToUpper();
        string result = "";

        if (EventoPartidoID == 0)
        {
            var existeEvento = _context.EventoPartidos.Where(e => e.PartidoID == PartidoID).Count();
            if (existeEvento == 0)
            {
                var nuevoEvento = new EventoPartido
                {
                    PartidoID = PartidoID,
                    FechaEvento = FechaEvento,
                    Descripcion = Descripcion
                };
                _context.Add(nuevoEvento);
                _context.SaveChanges();
                result = "agg";
            }
            else
            {
                result = "existe";
            }
        }
        else
        {
            var editarEvento = _context.EventoPartidos.Where(e => e.EventoPartidoID == EventoPartidoID).SingleOrDefault();
            if (editarEvento != null)
            {
                var existeEventoEditar = _context.EventoPartidos.Where(e => e.PartidoID == PartidoID).Count();
                if (existeEventoEditar == 0)
                {
                    editarEvento.PartidoID = PartidoID;
                    editarEvento.FechaEvento = FechaEvento;
                    editarEvento.Descripcion = Descripcion;
                    _context.SaveChanges();
                    result = "edit";
                }
                else {
                    result = "edit existente";
                }
            }
        }



        return Json(result);
    }

    public JsonResult EliminarEvento(int EventoPartidoID)
    {
        var eliminarEvento = _context.EventoPartidos.Find(EventoPartidoID);
        _context.Remove(eliminarEvento);
        _context.SaveChanges();

        return Json(eliminarEvento);
    }


}

Jugadores/Controllers/GraficosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Jugadores.Models;
using Jugadores.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Jugadores.Controllers;

public class GraficosController : Controller
{
    private ApplicationDbContext _context;

    public GraficosController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Graficos()
    {
        var jugadores = _context.Jugadores.ToList();
        
        jugadores.Add(new Jugador { JugadorID = 0, Nombre = "SELECCIONE UN JUGADOR..."});
        ViewBag.JugadorID = new SelectList(jugadores.OrderBy(j => j.JugadorID), "JugadorID", "Nombre");

        return View();
    }

    public JsonResult GraficoPartidosMes(int JugadorID, int Mes, int Anio)
    {
        List<PartidosPorDia> partidosPorDias = new List<PartidosPorDia>();

        var diasDelMes = DateTime.DaysInMonth(Anio, Mes);

        DateTime fechaMes = new DateTime();

        fechaMes = fechaMes.AddMonths(Mes - 1);

        for (int i = 1; i <= diasDelMes; i++)
        {
            var diaMesMostrar = new PartidosPorDia
            {
                Dia = i,
                Mes = fechaMes.ToString("MMM").ToUpper(),
                CantidadMinutos = 0
            };
            partidosPorDias.Add(diaMesMostrar);
        }

        var partidos = _context.Partidos.Where(p => p.JugadorID == JugadorID 
        && p.FechaPartido.Month == Mes && p.FechaPartido.Year == Anio).ToList();

        foreach (var partido in partidos.OrderBy(p => p.FechaPartido))
        {
            var partidoDiaMostrar = partidosPorDias.Where(p => p.Dia == partido.FechaPartido.Day).SingleOrDefault();
            if (partidoDiaMostrar != null)
            {
                partidoDiaMostrar.CantidadMinutos += Convert.ToInt32(partido.MinutosJugados);
            }
        }

        return Json(partidosPorDias);
    }
}

Jugadores/Controllers/JugadoresController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Jugadores.Models;
using Jugadores.Data;

namespace Jugadores.Controllers;

public class JugadoresController : Controller
{
    private ApplicationDbContext _context;

    public JugadoresController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Jugadores()
    {
        return View();
    }

    public JsonResult ListadoJugadores(int? JugadorID)
    {
        //listado de jugadores
        var jugadores = _context.Jugadores.ToList();
        jugadores = _context.Jugadores.OrderByDescending(j => j.AnioNacimiento).ToList();

        if (JugadorID != null)
        { //listado de jugadores por id 
            jugadores = _context.Jugadores.Where(j => j.JugadorID == JugadorID).ToList();
        }

        return Json(jugadores);
    }

    public JsonResult GuardarJugador(int JugadorID, string Nombre, string Puesto, int AnioNacimiento)
    {
        string resultado = "";

        Nombre = Nombre.ToUpper();
        Puesto = Puesto.ToUpper();

        if (JugadorID == 0)
        {
            var existenDatos = _context.Jugadores.Where(e => e.Nombre == Nombre).Count();
            if (existenDatos == 0)
            {
                var nuevoJugador = new Jugador
                {
                    Nombre = Nombre,
                    Puesto = Puesto,
                    AnioNacimiento = AnioNacimiento
                };
                _context.Add(nuevoJugador);
                _context.SaveChanges();
                resultado = "Jugador añadido correctamente!";
            }
            else
            {
                resultado = "Ya existe un jugador con este nombre";
            }
        }
        else
        {
            var editarJugador = _context.Jugadores.Where(e => e.JugadorID == JugadorID).SingleOrDefault();
            if (editarJugador != null)
            {

                var existeNombreJugador = _context.Jugadores.Where(e => e.Nombre == Nombre && e.JugadorID != JugadorID).Count();
                if (existeNombreJugador == 0)
                {
                    editarJugador.Nombre = Nombre;
                    editarJugador.Puesto = Puesto;
                    editarJugador.AnioNacimiento = AnioNacimiento;
                    _context.SaveChanges();
                    resultado = "Jugador editado correctamente!";
                }
                else
                {
                    resultado = "Este jugador ya existe";
                }
            }
        }

        return Json(resultado);
    }

    public JsonResult EliminarJugador(int JugadorID)
    {
        bool eliminado = false;

        var existeJugador = _context.Partidos.Where(e => e.JugadorID == JugadorID).Count();

        if (existeJugador == 0)
        {
            var eliminarJugador = _context.Jugadores.Find(JugadorID);
            _context.Remove(eliminarJugador);
            _context.SaveChanges();
            eliminado = true;
        }

        return Json(eliminado);
    }
}

Jugadores/Controllers/PartidosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Jugadores.Models;
using Jugadores.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Jugadores.Controllers;

public class PartidosController : Controller
{
    private ApplicationDbContext _context;

    public PartidosController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Partidos()
    {
        var jugadores = _context.Jugadores.ToList();

        jugadores.Add(new Jugador { JugadorID = 0, Nombre = "SELECCIONE UN JUGADOR..." });
        ViewBag.JugadorID = new SelectList(jugadores.OrderBy(j => j.JugadorID), "JugadorID", "Nombre");

        var JugadorIDBuscar = _context.Jugadores.ToList();

        JugadorIDBuscar.Add(new Jugador { JugadorID = 0, Nombre = "TODOS LOS JUGADORES" });
        ViewBag.JugadorIDBuscar = new SelectList(JugadorIDBuscar.OrderBy(j => j.JugadorID), "JugadorID", "Nombre");

        return View();
    }

    public JsonResult ListadoPartidos(int? PartidoID, int? JugadorIDBuscar, DateOnly FechaPartidoBuscar)
    {
        var listadoPartidos = _context.Partidos.Include(l => l.Jugador).ToList();

        if (PartidoID != null)
        {
            listadoPartidos = _context.Partidos.Where(l => l.PartidoID == PartidoID).ToList();
        }

        if (JugadorIDBuscar != null && JugadorIDBuscar != 0)
        {
            listadoPartidos = listadoPartidos.Where(l => l.JugadorID == JugadorIDBuscar).ToList();
        }

        var listadoPartidosMostrar = listadoPartidos.Select(l => new VistaPartidos
        {
            PartidoID = l.PartidoID,
            JugadorID = l.JugadorID,
            JugadorNombre = l.Jugador.Nombre,
            FechaPartido = l.FechaPartido,
            FechaPartidoString = l.FechaPartido.ToString("dd/MM/yyyy"),
            MinutosJugados = l.MinutosJugados,
            Estadio = l.Estadio
        }).ToList();

        return Json(listadoPartidosMostrar);
    }

    public JsonResult GuardarPartidos(int PartidoID, int JugadorID, DateOnly Fecha, decimal Minutos, string Estadio)
    {
        string resultado = "";
        if (PartidoID == 0)
        {
            var existePartido = _context.Partidos.Where(e => e.FechaPartido == Fecha).Count();
            if (existePartido == 0)
            {
                var nuevoPartido = new Partido
                {
                    JugadorID = JugadorID,
                    FechaPartido = Fecha,
                    MinutosJugados = Minutos,
                    Estadio = Estadio
                };
                _context.Add(nuevoPartido);
                _context.SaveChanges();
                resultado = "cheeeck";
            }
            else
            {
                resultado = "Este partido ya existe";
            }
        }
        else
        {
            var editarPartido = _context.Partidos.Where(e => e.PartidoID == PartidoID).SingleOrDefault();
            if (editarPartido != null)
            {
                var existePartidoEditar = _context.Partidos.Where(e => e.PartidoID != PartidoID && e.FechaPartido == Fecha).Count();
                if (existePartidoEditar == 0)
                {
                    editarPartido.JugadorID = JugadorID;
                    editarPartido.FechaPartido = Fecha;
                    editarPartido.MinutosJugados = Minutos;
                    editarPartido.Estadio = Estadio;
                    _context.SaveChanges();
                    resultado = "yess";
                }
                else
                {
                    resultado = "Este partido ya existe";
                }
            }
        }

        return Json(resultado);
    }

    public JsonResult EliminarPartido(int PartidoID)
    {
        var eliminarPartido = _context.Partidos.Find(PartidoID);
        _context.Remove(eliminarPartido);
        _context.SaveChanges();

        return Json(eliminarPartido);
    }
}

Jugadores/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jugadores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Jugadores.styles.css" asp-append-version="true" />
    <!-- Compiled and minified CSS -->
    @* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> *@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Jugadores</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jugadores" asp-action="Jugadores">Jugadores de Futbol</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Partidos" asp-action="Partidos">Partidos por Jugador</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eventos" asp-action="Eventos">Eventos por Partido</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Graficos" asp-action="Graficos">Estadisticas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InformeTablas" asp-action="InformeTablas">Informe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InformeTablas" asp-action="InformeTresNiveles">Informe de 3 niveles</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Jugadores - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- Compiled and minified JavaScript -->
    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>